config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
    },
    path_names: {
      sign_in: 'connexion',
      sign_out: 'deconnexion',
    },
    path: 'auth'

  mount Sidekiq::Web => '/sidekiq'

  root to: 'projects#index'

  namespace :api do
    resources :users, only: :index
    resources :projects, path: 'projets' do
      resources :assignments, only: [:index, :create, :destroy], path: 'membres'
      get 'assignable-users', to: 'assignments#assignable_users'
    end
  end

  resources :users,
    path: 'utilisateurs',
    path_names: { new: 'creer', edit: 'editer' } do
      resource :impersonation, only: [:create, :destroy], module: :users
    end

  resources :companies, path: 'groupes', path_names: { new: 'creer', edit: 'editer' }, except: :destroy do
    resources :employments, only: [:index, :create, :destroy], path: 'membres'
  end

  resources :projects, path: 'projets', path_names: { new: 'creer', edit: 'editer' } do
    resources :assignments, only: :index, path: 'membres'
    resources :folders, path: 'dossiers'
    resources :subscriptions
  end

  resources :documents
  resources :archives, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :invitable

  belongs_to :company

  has_many :documents
  has_many :folders

  has_many :subscriptions, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :employments, dependent: :destroy
  has_many :activities,  dependent: :destroy

  has_many :projects,  through: :assignments

  accepts_nested_attributes_for :employments, reject_if: lambda { |e| e[:company_id].blank? }, allow_destroy: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  validates :first_name, :last_name, :city, presence: true

  enum group: [ :partner, :employee, :admin ]

  def self.default_scope
    order('last_name ASC')
  end

  scope :search, ->(query) {
    if query.present?
      includes(:projects, :company)
        .where("unaccent(first_name) ILIKE unaccent(?) OR unaccent(last_name) ILIKE unaccent(?)", "%#{query}%", "%#{query}%")
    end
  }

  scope :assigned_to_project, ->(query) {
    if query.present?
      joins(:projects)
        .where("unaccent(projects.name) ILIKE unaccent(?)", "%#{query}%")
    end
  }

  scope :employed_by_company, ->(query) {
    if query.present?
      joins(:company)
        .where("unaccent(companies.name) ILIKE unaccent(?)", "%#{query}%")
    end
  }

  def self.unassigned_to_project(project_id)
    User
      .joins("LEFT OUTER JOIN assignments ON assignments.user_id = users.id AND assignments.project_id = #{project_id}")
      .where('assignments.id IS NULL')
  end

  def self.unemployed_by_company(company_id)
    User
      .joins("LEFT OUTER JOIN employments ON employments.user_id = users.id AND employments.company_id = #{company_id}")
      .where('employments.id IS NULL')
  end

  def full_name
    "#{last_name}, #{first_name}"
  end

  def projects_names
    projects.pluck(:name).join(", ")
  end

  def account_status
    self.active? ? "actif" : "inactif"
  end

  def active_for_authentication?
    super && self.active?
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  def index
    if filters?
      users = User.assigned_to_project(params[:project])
                  .employed_by_company(params[:company])
                  .search(params[:filter])

    else
      users = User.includes(:projects, :company)
    end

    render json: users
  end

  def filters?
    params[:project].present? || params[:company].present? || params[:filter].present?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/impersonations_controller.rb
class Users::ImpersonationsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    impersonate_user(user)
    redirect_to root_path
  end

  def destroy
    stop_impersonating_user
    redirect_to root_path
  end
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

class Users::InvitationsController < Devise::InvitationsController
  before_action :configure_permitted_parameters

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    email_admin
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite, keys: [:first_name, :last_name, :company_id, :group, :city])
  end

  def email_admin
    invitee = User.find_by_invitation_token(params[:user][:invitation_token], true)
    UserMailer.invitation_accepted(invitee).deliver_now
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super do |user|
      UserMailer.welcome_email(user).deliver_now
    end
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :city])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    update_attrs = [:status, :group, :first_name, :last_name, :city]
    devise_parameter_sanitizer.permit(:account_update, keys: update_attrs)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:projects, :company)

    @users_json =
      ActiveModelSerializers::SerializableResource.new(
        @users,
        each_serializer: UserSerializer
    ).as_json
  end

  def new
    @user = User.new
  end

  def create
    password = SecureRandom.hex
    password_params = { password: password }
    @user = User.new(user_params.merge(password_params))

    if @user.save
      redirect_to users_url, notice: 'Utilisateur créé avec succès.'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])

    if user.update(user_params)
      redirect_to user, notice: 'Modifications enregistrées.'
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url, notice: "Compte utilisateur supprimé."
  end

  def impersonate
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :first_name,
                                 :last_name,
                                 :city,
                                 :active,
                                 :group,
                                 :company_id
                                )
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def projects_for_select
    Project.all.map do |project|
      [project.name, project.id]
    end
  end

  def companies_for_select
    Company.all.map do |company|
      [company.name, company.id]
    end
  end

  def user_groups_for_select
    User.groups.map do |group|
      [t("activerecord.attributes.user.group.#{group.first}"), group.first]
    end
  end
end

app/views/users/_employment_fields.html.erb
<div class="field">
  <div class="control">
    <div class="select">
      <%= f.collection_select(:company_id, Company.all, :id, :name, prompt: true) %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">Editer compte</h2>

    <%= form_with(model: @user, local: true) do |form| %>
      <% if allow_param? :user, :active %>
        <div class="field">
          <div class="control">
            <label class="label" name="user[active]">Actif
              <%= form.check_box :active, id: :user_active, class: "checkbox" %>
            </label>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :group %>
        <div class="field">
          <%= form.label :group, "Niveau d'accès", class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.select :group do %>
                <%= options_for_select(user_groups_for_select, @user.group) %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :company, "Groupe", class: "label" %>
        <div class="control">
          <div class="select">
            <%= form.collection_select(:company_id, Company.all, :id, :name, prompt: true) %>
          </div>
        </div>
      </div>

      <% if allow_param? :user, :first_name %>
        <div class="field">
          <%= form.label :first_name, 'Prénom', class: "label" %>
          <div class="control">
            <%= form.text_field :first_name, class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :last_name %>
        <div class="field">
          <%= form.label :last_name, 'Nom', class: "label" %>
          <div class="control">
            <%= form.text_field :last_name, class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :email %>
        <div class="field">
          <%= form.label :email, class: "label" %>
          <div class="control">
            <%= form.email_field :email, autocomplete: "email", class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :city %>
        <div class="field">
          <%= form.label :city, 'Ville', class: "label" %>
          <div class="control">
            <%= form.text_field :city, class: "input" %>
          </div>
        </div>
      <% end %>

      <div class="actions">
        <%= form.submit "Valider", class: "button" %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<% content_for :tail_scripts do %>
  <%= javascript_pack_tag "users" %>
<% end %>

<section class="section">
  <div class="container">
    <h2 class="title is-2">Utilisateurs</h2>

    <%= content_tag :div,
      id: "users-elm-app",
      data: {
        users: @users_json,
        projectsEndpoint: api_projects_url,
        usersEndpoint: api_users_url
      }.to_json do %>
    <% end %>

    <hr />

    <% if allow_action? :users, :create %>
      <%= link_to 'Créer un nouvel utilisateur', new_user_url, class:"button is-primary" %>
    <% end %>

    <% if allow_action? :invitations, :create %>
      <%= link_to 'Créer une invitation', new_user_invitation_url, class:"button is-primary" %>
    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">Créer un nouveau compte utilisateur</h2>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "erreur", "erreurs") %>:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @user, local: true) do |form| %>
      <% if allow_param? :user, :active %>
        <div class="field">
          <div class="control">
            <label class="label" name="user[active]">Actif
              <%= form.check_box :active, id: :user_active, class: "checkbox" %>
            </label>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :group %>
        <div class="field">
          <%= form.label :group, "Niveau d'accès", class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.select :group do %>
                <%= options_for_select(user_groups_for_select, @user.group) %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :company, "Groupe", class: "label" %>
        <div class="control">
          <div class="select">
            <%= form.collection_select(:company_id, Company.all, :id, :name, prompt: true) %>
          </div>
        </div>
      </div>
      <% if allow_param? :user, :first_name %>
        <div class="field">
          <%= form.label :first_name, 'Prénom', class: "label" %>
          <div class="control">
            <%= form.text_field :first_name, class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :last_name %>
        <div class="field">
          <%= form.label :last_name, 'Nom', class: "label" %>
          <div class="control">
            <%= form.text_field :last_name, class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :email %>
        <div class="field">
          <%= form.label :email, class: "label" %>
          <div class="control">
            <%= form.email_field :email, autocomplete: "email", class: "input" %>
          </div>
        </div>
      <% end %>

      <% if allow_param? :user, :city %>
        <div class="field">
          <%= form.label :city, 'Ville', class: "label" %>
          <div class="control">
            <%= form.text_field :city, class: "input" %>
          </div>
        </div>
      <% end %>
      <div class="actions">
        <%= form.submit "Valider", class: "button is-primary" %>
      </div>

    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">
      <%= @user.full_name %>
    </h2>

    <div class="field is-grouped">
      <p class="control">
        <% if allow_action?(:users, :edit, @user) %>
          <%= link_to "Editer", edit_user_url(@user), class: "button" %>
        <% end %>
      </p>

      <p class="control">
        <% if allow_action?(:users, :impersonate) %>
          <%= button_to "Se connecter en tant que #{@user.first_name}", user_impersonation_path(@user), method: :post, class: "button" %>
        <% end %>
      </p>
    </div>

    <div class="content">
    </div>

    <table class="table">
      <tbody>
        <tr>
          <th>
            Statut du compte
          </th>
          <td>
            <%= @user.account_status %>
          </td>
        </tr>
        <tr>
          <th>
            Niveau d'accès
          </th>
          <td>
            <%= t "activerecord.attributes.user.group.#{@user.group}" %>
          </td>
        </tr>
        <tr>
          <th>
            Email
          </th>
          <td>
            <%= @user.email %>
          </td>
        </tr>
        <tr>
          <th>
            Ville
          </th>
          <td>
            <%= @user.city %>
          </td>
        </tr>
        <tr>
          <th>
            Groupe
          </th>
          <td>
            <%= link_to @user.company.name, @user.company %>
          </td>
        </tr>
      </tbody>
    </table>

    <% if allow_action?(:users, :destroy, @user) %>
      <%= button_to "Supprimer", @user, method: :delete, data: { confirm: "Etes-vous sur de vouloir supprimer ce compte ?" }, class: "button is-danger" %>
    <% end %>
  </div>
</section