config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      invitations: 'users/invitations'
    },
    path_names: {
      sign_in: 'connexion',
      sign_out: 'deconnexion',
    },
    path: 'auth'

  mount Sidekiq::Web => '/sidekiq'

  root to: 'projects#index'

  namespace :api do
    resources :users, only: :index
    resources :projects, path: 'projets' do
      resources :assignments, only: [:index, :create, :destroy], path: 'membres'
      get 'assignable-users', to: 'assignments#assignable_users'
    end
  end

  resources :users,
    path: 'utilisateurs',
    path_names: { new: 'creer', edit: 'editer' } do
      resource :impersonation, only: [:create, :destroy], module: :users
    end

  resources :companies, path: 'groupes', path_names: { new: 'creer', edit: 'editer' }, except: :destroy do
    resources :employments, only: [:index, :create, :destroy], path: 'membres'
  end

  resources :projects, path: 'projets', path_names: { new: 'creer', edit: 'editer' } do
    resources :assignments, only: :index, path: 'membres'
    resources :folders, path: 'dossiers'
    resources :subscriptions
  end

  resources :documents
  resources :archives, only: [:index, :create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments
  has_many :subscriptions, as: :subscribeable
  has_many :subscribers, through: :subscriptions

  has_one :root_folder, ->{ where(ancestry: nil) }, class_name: "Folder", dependent: :destroy

  validates :name, presence: true

  enum status: [ :active, :archived ]

  scope :active,   ->{ where(status: "active") }
  scope :archived, ->{ where(status: "archived") }

  def self.default_scope
    order('name ASC')
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::ApiController
  def index
    projects = Project.where("name ILIKE ?", "%#{params[:query]}%")
    render json: projects
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = show_all_projects? ? Project.active.includes(:subscriptions) : current_user.projects.active.includes(:subscriptions)
  end

  def show
    redirect_to project_folder_path(current_resource, current_resource.root_folder)
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.new(project_params)
    folder = Folder.new(
      name: "#{project.name}",
      project: project,
      user: current_user
    )

    ActiveRecord::Base.transaction do
      project.save!
      folder.save!
    end

    redirect_to projects_url, notice: 'Projet créé avec succès.'
  end

  def edit
    @project = current_resource
  end

  def update
    project = current_resource

    if project.update(project_params)
      project.root_folder.update(name: project.name)
      redirect_to projects_url, notice: 'Modifications enregistrées.'
    else
      render :edit
    end
  end

  def destroy
    project = current_resource
    project.destroy
    redirect_to projects_url, notice: "Projet #{project.name} supprimé."
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def current_resource
    @current_resource ||= Project.find(params[:id]) if params[:id]
  end

  def show_all_projects?
    current_user.admin? || current_user.employee?
  end
end

app/views/projects/_controls.html.erb
<div class="columns">
  <div class="column">
    <% if subscription.present? %>
      <%= button_to project_subscription_url(project, subscription), class: "button is-small", method: :delete do %>
        <span class="icon is-small has-text-danger">
          <i class="fas fa-users"></i>
        </span>
        <span>Arrêter de suivre</span>
      <% end %>
    <% else %>
      <%= button_to project_subscriptions_url(project), class: "button is-small", method: :post do %>
        <span class="icon is-small has-text-success">
          <i class="fas fa-users"></i>
        </span>
        <span>Suivre</span>
      <% end %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :projects, :edit %>
      <%= link_to "Editer", edit_project_url(project), class: "button is-small" %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :assignments, :create %>
      <%= link_to "Gérer les membres", project_assignments_path(project), class: "button is-small" %>
    <% end %>
  </div>

  <div class="column">
    <% if project.active? %>
      <% if allow_action? :archives, :create %>
        <%= button_to "Archiver", archives_path(project_id: project.id), method: :post, class: "button is-small" %>
      <% end %>
    <% end %>

    <% if project.archived? %>
      <% if allow_action? :archives, :destroy %>
        <%= button_to "Désarchiver", archive_path(project.id), method: :delete, class: "button is-small" %>
      <% end %>
    <% end %>
  </div>

  <div class="column">
    <% if allow_action? :projects, :delete %>
      <%= button_to "Supprimer", project, method: :delete, class: "button is-small is-danger" %>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "erreur", "erreurs") %>:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nom', class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input", autofocus: true %>
    </div>
  </div>

  <div class="control">
    <%= form.submit action_name == 'new' ? 'Créer' : 'Valider', class: "button is-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">Editer le projet '<%= @project.name %>'</h2>

    <%= render 'form', project: @project %>
  </div>
</section>

app/views/projects/index.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-2">Projets</h2>

    <% @projects.each do |project| %>
      <div class="columns">
        <div class="column is-one-half">
          <%= link_to project.root_folder.name, project_folder_url(project, project.root_folder) %>
        </div>

        <div class="column">
          <%= render 'controls',
            project: project,
            subscription: project.subscriptions.find_by(subscriber: current_user, subscribeable: project) %>
        </div>
      </div>
    <% end %>

    <% if allow_action? :projects, :new %>
      <%= link_to 'Créer un nouveau projet', new_project_url, class:"button is-primary" %>
    <% end %>
  </div>
</section>

app/views/projects/new.html.erb
<section class="section">
  <div class="container">
    <%= tag.h1 'Créer un nouveau projet', class: "title is-1" %>

    <%= render 'form', project: @project %>
  </div>
</section>

app/views/projects/show.html.erb
<section class="section">
  <div class="container">
    <%= tag.h1 @project.name, class: "title is-1" %>

    <div class="content">
      <%= render 'controls', project: @project %>

      <hr />

      <table class="table">
        <tbody>
          <% @project.root_folder.children.each do |folder| %>
            <tr>
              <td class="is-narrow">
                <span class="icon">
                  <i class="far fa-folder"></i>
                </span>
              </td>
              <td><%= link_to folder.name, project_folder_path(@project, folder) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <% if allow_action? :folders, :create %>
      <hr />

      <div class="content">
        <h3 class="title is-3">Créer un nouveau dossier</h3>

        <%= form_with(model: [@project, @folder], local: true) do |f| %>
          <% if @folder.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@folder.errors.count, "erreur", "erreurs") %>:</h2>

              <ul>
                <% @folder.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.label :name, class: "label" %>

          <div class="field">
            <div class="control">
              <%= f.text_field :name, class: "input", placeholder: "Nom de dossier" %>
              <%= f.hidden_field :project_id, value: @project.id %>
            </div>
          </div>

          <div class="control">
            <%= f.submit "Créer", class: "button is-primary" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>